spring:
  profiles:
    active: dev
  messages:
    basename: i18n/message
    encoding: UTF-8 
       
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    
mybatis:
  mapper-locations: classpath:/sql/sample/*.xml
  configuration.map-underscore-to-camel-case: true
  type-aliases-package: com.example.vo
  
server:
  port: ${PORT:5000}

graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
  datetime:
    scalars:
      zone-conversion-enabled: true  
    
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /api/graphql
  cdn:
    enabled: true
    version: 0.12.0
  headers:
    Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJSU00iLCJleHAiOjE1NjU3NTMzNjksImlhdCI6MTU2NTMyMTM2OX0.2_0f33-6RVNS--A1qmEqiu6hvhw1uOxzWc4pfxQv1ak"  

---
  
spring:
  profiles: dev  
  datasource:
    url: jdbc:postgresql://10.211.55.10:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

---

spring:
  profiles: prd  
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10